### 1. LUODAAN UUSI KÄYTTÄJÄ (Huom: Nyt sähköposti on pakollinen ja salasana min 8 merkkiä)
# @name register
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name": "Testi Käyttäjä",
    "username": "testaajauusi",
    "email": "testi@metropolia.fi",
    "password": "salaisuus123",
    "role": "user"
}

### 2. KIRJAUDU SISÄÄN
# @name login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "testaaja_uusi",
    "password": "salaisuus123"
}

### TALLENNETAAN TOKEN MUUTTUJAAN
@token = {{login.response.body.token}}

### 3. TESTAA TOKEN (ME-REITTI)
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer {{token}}

### 4. LISÄÄ KISSA
POST http://localhost:3000/api/v1/cats
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Misu
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="owner"

38
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="cat"; filename="kissa.jpg"
Content-Type: image/jpeg

< ./public/kissa.jpg
--MyBoundary--